project:
  type: website
  render:
    - "*.qmd"
    - "weeks/"
    - "workshops/"
    - "!slides/"
    - "!solutions/"
    - "!exams/"
  output-dir: _site

website:
  #announcement: 
    # icon: emoji-smile
    # dismissable: true
    # type: info
    # content: "Bonne vacances"
    # position: above-navbar
  page-navigation: true
  title: "MA15Y030 - Automne 2025"
  description: "Page maison pour MA15Y030 - Bases de données, Licence MIASHS Automne  2025."
  site-url: "https://bgentou.github.io/MA15E045/"
  repo-url: "https://github.com/bgentou/MA15E045"
  repo-actions: [edit, issue]

  open-graph: true

  page-footer:
    right: "This page is built with blood, sweat, tears, and [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2025, Stéphane Boucheron & Bertrand Gentou"
    background: "#D9E3E4"

  sidebar:
    background: "#D9E3E4"
    logo: "images/logo.png"
    pinned: true
    align: center
    tools:
      - icon: github
        href: https://github.com/bgentou/MA15E045
        text: "GitHub organization"
      - icon: person-fill
        href: https://moodle.u-paris.fr/course/view.php?id=2313
        text: "Moodle"
        menu:
          - text: Discussion forum
            url: https://moodle.u-paris.fr/course/view.php?id=2313
          - text: Dépot 
            url: https://moodle.u-paris.fr/course/view.php?id=2313
          - text: Notes
            url: https://moodle.u-paris.fr/course/view.php?id=2313

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Informations générales
      # - section: "Informations générales"
      #   contents:
      #     - href: index.qmd
      #       text: Aperçu
      #     - href: cours-syllabus.qmd
      #       text: Syllabus
      #     - href: cours-equipe.qmd
      #       text: Équipe
      - section: "Support"
        contents:
          - href: computing-access.qmd
            text: "Accès Informatique"
          - href: computing-dbeaver.qmd
            text: "Client dbeaver"
          - href: computing-pgcli.qmd
            text: "Client pgcli"
          - href: computing-psql.qmd
            text: "Client psql"  
      - href: slides-listings.qmd
        text: Diapositives
      - href: td-listings.qmd
        text: Exercices
      # - href: corriges-tds.qmd
      #   text: Corrections  
      - href: schemas-listings.qmd
        htext: Schémas
      - href: exams-listings.qmd
        text: Annales
      - href: journal-listings.qmd
        htext: Journal

format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true
    link-external-newwindow: true

execute:
  freeze: auto
  cache: true

editor: source
