params:
    year: 2025 
    curriculum: "L3 MIASHS/Ingémath"
    university: "[Université Paris Cité](https://www.u-paris.fr)"
    homepage: "[Course Homepage](https://bgentou.github.io/MA15E045/)"
    moodle: "[Moodle](https://moodle.u-paris.fr/course/view.php?id=2313)"
